version: 2
updates:
  - package-ecosystem: nuget
    directory: /src
    schedule:
      interval: weekly
    groups:
      avalonia:
        patterns:
          - "Avalonia*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
